### ISSUE TITLE
Code review životopis

### ISSUE THREAD

**Issue by ViktoriaAndr** [Wierra/01_Zivotopis#1]
Ahoj,
pekná práca. Pár poznámok ku kódu:

- je zvykom označovať triedy v angličtine, ale to je len taká mini poznámka.
- odkazy v kóde sú defaultne podtrhnuté. Aby podtrhnuté neboli, použi `text-decoration: none` pre tvoju e-mailovú adresu

**Comment by Wierra** [comment]
Ahoj Viki, 
děkuji Ti za připomínky, beru na vědomí :).
